version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    env_file:
      - .env

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxcdfrt56
      POSTGRES_DB: online_school
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d online_school
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config worker -l info
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l info
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env


volumes:
  pg_data:
